# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build And Deploy To Azure

on:
  pull_request:
    branches:
      - production
    types: [closed]
  workflow_dispatch:

jobs:
  install-npm-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Checkout Github Repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false #otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token. 
          fetch-depth: 0

      - name: Set up Node.js version
        uses: actions/setup-node@v3.5.0
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: Install npm dependencies
        run: |
          npm ci

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BEA95B8E957541C1B27907E81965510A }}
          package: .